import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div>
      <Head>
        <title>What does the Twitter think?</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="h-screen flex justify-center mt-12">
        <div className="flex flex-col">
          <h1 className="font-bold text-5xl ">What does the Twitter think?</h1>
          <input type="text" className="w-[50%] mx-auto mt-5 pr-2 rounded-xl h-[5%]" />
        </div>
      </main>
    </div>
  );
}
